- docs/contributing.mdx
I reworded some parts of the contribution guide because it made references to the internal systems.
> docs(contributing): remove references to internal systems

- package-lock.json
- package.json
- tsconfig.json
At the moment we use standard TypeScript transpiler for styled-components. In that setup server-side rendering does not work as expected.
The PR uses the approach mentioned in the styled-components documentation
> Use a dedicated transpiler for styled-components

- docs/index.mdx
- doczrc.js
Removed SECURITY and MAINTAINERS page which were added
accidentally, as well as a link to intenal slack.
> docs: removed some pages and internal references

- src/components/Pagination/Pagination.tsx
**What**
When the `Pagination` component gets 0 items "nextPage" and "skipToLastPage" buttons are not disabled.
**Why**
When the component gets 0 items `isLastPage` is never true, because `totalItems / pageSize` with `totalItems === 0` gives `0` and `value` (the current page) must be `>= 1`.
**How**
In the case we don't have items `!totalItems`, then `isLastPage` is set to true.
> fix: isLastPage true if 0 items

- src/components/Input/Input.tsx
- src/components/Textarea/Textarea.tsx
**What:**
During the investigation of #71 we noticed that `Input` and `Textarea` don't render on codesandbox. This affects only users of the ESM version of the library.
​
**Why:**
Fixes a potentially live bug.
​
**How:**
Both components used a named import for `React` by using `import { default as React } from "react"`. I changed this to `import React from "react"`.
> fix: use default export instead of named export

- docs/release-notes.mdx
- src/components/Table/components/TableCell.tsx
- src/components/Table/components/TableHeaderCell.tsx
**What:**
Add textAlign prop to `TableCell` and `TableCellHeader` components
​
**Why:**
closes #70 
​
**How:**
Use styled-system API and compose components with textAlign
​
**Media:**
**Checklist:**
> Allow textAlign on TableCell components

- docs/release-notes.mdx
- src/components/Datepicker/__snapshots__/DatepickerRangeInput.spec.tsx.snap
- src/components/Datepicker/__snapshots__/DatepickerSingleInput.spec.tsx.snap
- src/components/Input/BoxedInput.ts
- src/components/Input/__snapshots__/Input.spec.tsx.snap
- src/components/Textarea/__snapshots__/Textarea.spec.tsx.snap
**What:**
Allow label background to "respect" host background-color
​
**Why:**
Closes #14​
**How:**
Apply a gradient of 50%/50% that will take half of the label + _(hardcoded value check note [1])_
**Media:**
**Checklist:**
**Note:**
1. There are two variables taking place here. `fontSize`, `top` both of them change with the `size` attribute and the units themselves are odd numbers `0.375rem` or `0.75rem` this makes it harder to create a deterministic number instead of a "magic" one. The normal variant size medium will work great with `0.0625rem` matching the inset value but once the size small take place _I got confused_
2. I have a `TS` issue in regards to the prop.size in which the value is not mapped to `small` | `medium`
> Any suggestions/help to fix or improve these two points above …
> Update label background for boxed input variant

- src/essentials/theme.ts
**What:**
Align theme shadows scale to the initial design
​
**Why:**
Fixes #82
**Media:**
**Checklist:**
> Uses correct blur-radius value for medium size shadow

- docs/release-notes.mdx
- src/components/InlineSpinner/InlineSpinner.tsx
- src/components/InlineSpinner/__snapshots__/InlineSpinner.spec.tsx.snap
**What:**
Allow `InlineSpinner` to render as other icons when placed alongside a text
​
**Why:**
Relates #22 
In some cases when the spinner is being rendered with text it breaks the layout
​
**How:**
Wrap the icon with `span` _(as changing the div with span doesn't solve the issue)_ so we can reproduce the scenario similar to https://codesandbox.io/s/button-spinner-issue-wnmgv?file=/src/App.tsx
**Checklist:**
**Note:**
_I am a bit hesitant with the approach but at the same time I think It will solve the issue and there is no clear drawbacks I can see_
> Inline spinner update

- package-lock.json
- package.json
- src/components/Datepicker/__snapshots__/DatepickerRangeInput.spec.tsx.snap
- src/components/Datepicker/__snapshots__/DatepickerSingleInput.spec.tsx.snap
- src/components/Input/Input.spec.tsx
- src/components/Input/Input.tsx
- src/components/Input/__snapshots__/Input.spec.tsx.snap
- src/components/Select/Select.tsx
- src/components/Select/__snapshots__/Select.spec.tsx.snap
- src/components/Textarea/Textarea.spec.tsx
- src/components/Textarea/Textarea.tsx
- src/components/Textarea/__snapshots__/Textarea.spec.tsx.snap
- src/utils/__mocks__/ids.ts
- src/utils/hooks/useGeneratedId.ts
- src/utils/ids.ts
- src/utils/testing.ts
**What:**
Fixes critical accessibility issue for `Input`, `Textarea` and `Select`. Always links input to the corresponding labels
​
**Why:**
It is recommended to have inputs and corresponding labels linked. The input must provide an `id` and label references this id in the `for` attribute.
In the mentioned above components we create this relation only when the developer passed `id` property to the component. If not, the component seriously violates [the accessibility guidelines about the labels](https://dequeuniversity.com/rules/axe/4.2/label)
**How:**
New dependency [nanoid](https://github.com/ai/nanoid) which is 108 bytes minified and gzipped.
1. If the user provides an `id` prop we use it as an id
2. If not, but there is no label, do nothing
3. If not, and the label exists, generate a …
> Link inputs and labels when `id` is not provided by the user

- docs/accessibility.mdx
- doczrc.js
**What:**
Add a page for "Accessibility"
​
**Why:**
The idea is to provide guidance on how to include a11y in the implementation phase and also to make transparent our expectations on this subject.
​
**Media:**
[New page for Accessibility overview](https://user-images.githubusercontent.com/1425162/119520930-00fade00-bd7b-11eb-8f5e-e2ff69c69039.png)
**Checklist:**
**Notes:**
I open the PR with the idea to bring the conversation async taking some assumptions from past decisions and conversations.
**Useful links:**
I found it useful to take a look at other people work such as:
- https://design-system.service.gov.uk/
- https://speakerdeck.com/bennoloewenberg/accessibility-in-design-systems-english
- https://www.carbondesignsystem.com/guidelines/accessibility/overview
_In the future we can …
> docs(a11y): add a section to help over a11y

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/request.md
**What:**
Add templates to structure the issues submitted
​
**Why:**
There are some conversations and feedback process that can be optimized once we have a specific structure
​
**How:**
_I follow similar approaches as `react-testing-library`_
​
**Media:**
The idea is to achieve something like the image below:
**Checklist:**
> docs(templates): add issue templates

- src/components/Text/Text.spec.tsx
- src/components/Text/Text.tsx
- src/components/Text/docs/Text.mdx
**What:**
This PR adds the `disabled` state to the `Text` component, in alignment with the design for wave. It also fixes colors when `inverted` (for `weak` and `disabled` texts) also in alignment with the design.
​
**Why:**
This is in regard to [SUP-11112](https://jira.intapps.it/browse/SUP-11112)
​
**How:**
* Add a new disabled property to the `Text` component
* Fix the colors for inverted state
* Add examples to the documentation
​
**Media:**
> improvement: adding the disabled text color, fixing inverted text colors

- src/components/Checkbox/Checkbox.tsx
- src/components/Text/Text.spec.tsx
- src/components/Text/Text.tsx
- src/components/Text/docs/Text.mdx
**What:**
This PR fixes the color of the text of the `disabled` state for the `Checbox` component.
​
**Why:**
This is in regard to [SUP-11111](https://jira.intapps.it/browse/SUP-11111)
​
**How:**
* Pass the `disabled` property to the `Text` component inside `Checkbox`
​
**Media:**
> Note: This PR should ideally be merged only after [the preceding one](https://github.com/freenowtech/wave/pull/96) is merged, so that we can isolate changes in the merge commit with the ticket (currently, changes for [SUP-11112](https://jira.intapps.it/browse/SUP-11112) are included here as well)
> Adds disabled checkbox text color

- src/components/Password/Password.tsx
- src/components/Password/docs/Password.mdx
Fixes the issue when the `Password` component does not take the full width of the container, when `width="100%"` is set.
​
Closes #100 
The password component has two wrappers: 
* the outer wrapper containing the input and the show password button
* the inner wrapper with the input element with the label.
We passed all the props, including width, to the inner one. That caused issues when we want to set the width of the component. The width value was passed to the inner wrapper → the width of the input is changing, but not the width of the whole component.
The solution was to set the inner wrapper to fill the whole outer wrapper and pass width and margin props to the outer wrapper. In that case, we have two wrappers controlled by the outer one.
​
Demo: …
> Fixes Password component do not react on `width` property

- docs/changelog.mdx
- release.config.js
**What:**
Remove the auto-generate changelog title from the semantic-release/changelog plugin, fixes (partly) #106.
​
**Why:**
With the introduction of semantic-release, we moved the changelog generation to the automated process. Currently it (wrongly) adds the changelog title field for every changelog entry, leading to a broken build of the documentation.
​
**How:**
Removing the generated header will allow the changelog file to just contain markdown, which will not lead to build issues.
​
**Media:**
**Checklist:**
> docs: remove badly generated changelog title

- src/components/InlineSpinner/InlineSpinner.tsx
- src/components/InlineSpinner/__snapshots__/InlineSpinner.spec.tsx.snap
**What:**
Re-enable all props for the InlineSpinner component and fixed the tests, so we don't break it again 👀 
​
**Why:**
We introduced a wrapper element for the InlineSpinner in #77, but didn't forward the props for margin and size. This resulted in typescript projects that set the margin to break. All other projects would simply lose their set margins and sizes. @nlopin already found the issue with the sizes in #95, which this PR closes as well.
​
**How:**
Instead of wrapping the `div` element with `span`, we set the original element to `span`.
​
**Checklist:**
> fix: allow props to change the inline spinner again

- src/components/Headline/Headline.spec.tsx
- src/components/Headline/Headline.tsx
- src/components/Headline/docs/Headline.mdx
- src/components/Headline/docs/HeadlinePropsTable.tsx
**What:**
Allow influencing the size without changing the headline level.
​
**Why:**
Closes #17 
**How:**
Expose the `size` prop which takes precedence over the default headline level style
​
**Checklist:**
This is not a breaking change. The components without `size` prop set will still behave as in previous versions
> Separates headline styles from heading level

- src/components/Datepicker/DatepickerRangeInput.tsx
- src/components/Datepicker/DatepickerSingleInput.tsx
**What:**
​This PR enables emitting the click event on input fields inside the `Datepicker` component, for both (single and range) variants.
**Why:**
​This is to keep in line with expected behavior, as datepicker components consist of an input field or two, depending on the variant, and so must detect the click.
**How:**
​Remove the `event.stopPropagation()` method call from the `Input` component `onClick` attribute
**Media:**
https://www.loom.com/share/29d22680ca7e4db0a9d16036996a7f71
**Checklist:**
> fix: emitting input click events for datepicker

- src/components/Checkbox/Checkbox.spec.tsx
- src/components/Checkbox/Checkbox.tsx
**What:**
​This PR intends to fix an issue with checkboxes, where two clicks are registered instead of one
**Why:**
​This was causing weird behavior with Google Tag Manager data capturing, and so I decided to investigate. The issue seems to be because of a click being registered on the inner `Text` component
**How:**
​Prevent the event from being propogated in order to fix this issue
**Media:**
https://www.loom.com/share/05dffc1f667d435b9bfdbba4c3dd1ee7
**Checklist:**
> fix: preventing double clicks for the checkboxes

- src/components/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
- src/components/Checkbox/components/Checkmark.tsx
**What:**
Improve keyboard a11y of checkbox 
​
**Why:**
Closes #23 
​
**How:**
Remove the outline "none" and keep built-in one
​
**Media:**
**Checklist:**
> fix(checkbox): remove outline: none;

- src/gatsby-theme-docz/components/Header/index.js
- src/gatsby-theme-docz/components/Layout/index.js
- src/gatsby-theme-docz/components/MainContainer/index.js
**What:**
Improve content keyboard accessibility
​
**Why:**
We don't want to tab through the whole list of components to react the content
**How:**
Add [skip link](https://webaim.org/techniques/skipnav) to the header of the documentation page
To reach the skip link, use the Tab key on the keyboard.
​
**Media:**
https://www.loom.com/share/4172315357eb4b84a42b3fb818e37386
**Checklist:**
> Adds skip to content link to the Wave Web

- src/components/Datepicker/DatepickerRangeInput.tsx
- src/components/Datepicker/DatepickerSingleInput.tsx
**What:** This PR intends to enable passing of the `inputId` as props for the `DatePicker` component
​
**Why:** This is to give the end user more control over the form elements
​
**Media:** Nothing to see here
**Checklist:**
> improvement: making input ids passable by props for datepicker

- src/components/Label/Label.spec.tsx
- src/components/Label/Label.tsx
- src/components/Label/docs/Label.mdx
- src/components/Label/docs/LabelPropsTable.tsx
**What:**
Adding new label color "info" and "warning" in addition to the ability to give all labels a more prominent style with the "filled" prop. Closes #2 .
​
**Why:**
Some of the recent designs include additional label styles that are used in tables across our tools. Currently they are Label components with custom styles. To provide a common and reusable pattern, we want to include these styles in the library.
​​
**Media:**
**Checklist:**
**Other:**
This will change the styling of the variant "info" from grey to blue, while introducing a new variant (default) to replace the grey styles. The change can lead to unexpected colours of the label when the variant is explicitly specified. It will not cause any issue when no variant is specified, as the default looks identical.
> feat: add new label variants and filled prop

- src/components/Table/components/TableRowSkeleton.spec.tsx
- src/components/Table/components/TableRowSkeleton.tsx
**What:** This PR adds an `aria-label` property to elements rendered by `TableRowSkeleton` to enable accessibility testing
​
**Why:** This addresses issue #80 
​
**How:**
​1. Add an `aria-label` property to `Skeleton` elements rendered by `TableRowSkeleton`
2. Set `aria-hidden` to `true` as this is not something you want screen readers to pick up
3. Update tests.
**Media:** Nothing to see here
**Checklist:**
> improvement: adding aria-label to items rendered by TableRowSkeleton

- src/components/Datepicker/DatepickerRangeInput.tsx
**What:** This PR intends to add a `variant` property to the datepicker
​
**Why:** This is introduced to enable developers to decide whether to show only a single month or two months, according to their needs, without breaking the current responsive behavior.
​
**How:**
1. Create a prop `variant`
​
**Media:** https://www.loom.com/share/9cf8700746d14419a0c4610face30006
**Checklist:**
> improvement: adding a prop called variant for datepicker range

- docs/browser-support.mdx
- doczrc.js
- package.json
- src/index.ts
- src/polyfills.ts
**What:**
Adding a polyfill for IE11 and the Crypto api, closing #131.
​
**Why:**
After introducing the automatically generated ids for Input components using `nanoid`, we noticed a sharp increase of errors in our project. With some investigation, we found that nanoid requires the crypto api to be available on `window.crypto` (https://github.com/ai/nanoid#ie).
​
**How:**
Adding a specific `polyfill.ts` file to include this change to make IE 11 work with the design system again without throwing errors.
> Add the crypto api polyfill for IE 11

- src/components/Label/Label.spec.tsx
Since the PR #125 was merged a little bit prematurely, I haven't had a chance to address the code review comments. This fixes the wrong spelling of the css property when testing for a specific Label version.
> Fixes the spelling of the css property in the test

- release.config.js
**What:**
This PR adds `next` to the list of branches for semantic release.
​
**Why:**
In order to prepare the next major version we want to release automated preview versions. Therefore we can create a `next` branch which should be in sync with `main`. Breaking changes should be done only in `next` branch. When we made all the changes (TBD) for v2 then we can merge `next` back to `main`.
​
**How:**
Add `next` to the semantic release branches.
**Checklist:**
> ci: add release config for next branch

- src/components/Select/Select.spec.tsx
- src/components/Select/Select.tsx
- src/components/Select/docs/Select.mdx
- src/components/Select/docs/SelectPropsTable.tsx
**What:**
Adding a placeholder for the select component, closing #11.
​
**Why:**
The placeholder allows users to un-select an option in a select list.
**Media:**
**Checklist:**
> feat: add placeholder for the select component

- fixtures/babel-build/package-lock.json
- fixtures/babel-build/package.json
- fixtures/babel-build/webpack.config.js
- fixtures/typescript-build/package-lock.json
- fixtures/typescript-build/package.json
- fixtures/typescript-build/webpack.config.js
We have some dependencies in the test fixtures of this project, which are detected by Github. This does not have any impact on the compiled version or actual source, it's just related to our tests (no need to worry here).
**What:** Update dependencies for test fixtures (mainly upgrading from webpack 4 to version 5).
​
**Why:** So we can remove the dependabot alerts from this repository, which will allow us to detect if we encounter an actual security issue much easier.
​
**How:** Upgrading webpack and plugins for the test fixture projects
> Update test fixture dependencies (webpack)

- src/docs/PropsTable.tsx
- src/icons/docs/IconGrid.tsx
- src/icons/docs/IconPropsTable.tsx
- src/icons/docs/Icons.mdx
- src/icons/docs/SearchableIconGrid.tsx
Adding additional documentation for the exported icons with a searchable icon list and a couple of explanations on how to use the Icon and Flag components. Closes #15 
​​
> docs: update icon documentation to include examples and more details

- .github/workflows/library.yml
While adding the configuration to also release the @next version of wave, I noticed that the next branch has gotten behind `main`. Here I am adding a new action to merge the main branch into next when changes are pushed to it.
> chore: add action to merge main into next

- .github/workflows/library.yml
- codemods/v2.ts
- docs/migrating.mdx
- doczrc.js
- fixtures/typescript-build/src/index.tsx
- package-lock.json
- package.json
- src/components/Button/BaseButton.tsx
This is the first of a few PRs to mark the next major version for wave. I have introduced a migration guide and a codemod framework, which we can use to enable developers to seamlessly migrate to the next major version.
It's using `jscodeshift` to transform the files, which is the de-facto standard when it comes to writing codemods for javascript-based projects. Tried it in three projects and found a few places that were still using the `block` property. 
Let me know what you think of this approach and if you're willing to invest the time of writing codemods for all breaking changes. From experience, having a migration guide is so helpful when upgrading to a new version, because you don't have to dig through all the changes to figure out all the changes you have to perform.
I will also …
> feat: remove the deprecated block property for buttons

- release.config.js
**What:**
Add flag to publish pre-releases from `next` branch
​
**Why:**
We don't want to accidentally publish the next major version.
​
**How:**
Use `prerelease` option in `semantic-release`
**Checklist:**
> ci: add prerelease flag for next branch

- src/components/Toggle/Input.tsx
- src/components/Toggle/__snapshots__/Toggle.spec.tsx.snap
**What:**
Remove default margin for `Toggle` component
​
**Why:**
The `Toggle` component had an unexpected margin on the left.
Closes #167 
​
**How:**
- Set margin as 0 for `Toggle` component's inner `Input`
- Update snapshots​
**Media:**
The margin before
> fix: remove Toggle margin

- .github/PULL_REQUEST_TEMPLATE.md
**What:**
Add explanation on what to do with visual changes: add new design-review label.​
**Why:**
To allow designers to review changes that they are able to properly review. It helps them prioritise their work without having to look through all technical PRs.
​
> docs: update PR template for GitHub

- src/components/Headline/Headline.tsx
- src/components/Headline/docs/Headline.mdx
**What:**
Change the size of the headline depending on the viewport size. 
You can pass a responsive value to the `size` prop of the `Headline` component and it will change the size depending on the viewport.  For example, `<Headline size={{_: 's', m: 'xl'}}`>headline</Headline>`.
​
**Why:**
Closes #189
​
**How:**
* Used `system` function from the `styled-system` to define the list of possible values for headline CSS properties `line-height` and `font-size`
* Pass the `size` prop to the style function returned by `system` to get responsive styles
​
**Media:**
https://www.loom.com/share/62e01f42c7d1449e9adbf1a7eb227db6
**Checklist:**
> Support responsive `size` values for Headline

- src/essentials/Colors/Colors.ts
As we discussed on the sync, we want to separate branding colors from semantic tokens
​
**How:**
* remove `brand` section of the semantic color object (I searched the codebase, it is not used)
**Checklist:**
Since it is not used in the codebase, let's make it a minor release even though technically it is a breaking change.
> Remove brand colors from semantic tokens

- .stylelintrc
- src/components/Divider/Divider.spec.tsx
- src/components/Divider/Divider.tsx
- src/components/Divider/docs/Divider.mdx
- src/components/Divider/docs/WrappedDivider.tsx
- src/components/index.ts
**What:**
This PR adds a new Divider component to the Wave Design System, as per: [#218](https://github.com/freenowtech/wave/issues/218)
​
**Why:**
Closes #218 
A number of our tools that use Wave DS, including BOMT, DMT, PMT (and possibly more) have many instances of a horizontal or vertical line separating pieces of content. A Divider component is often a core component in design systems, therefore, this issue proposed the addition of new component to our Wave design system for these and other use-cases.
​
​
**Media:**
**Checklist:**
-   [x] Reviewed with designer
-   [x] Ready to merge
> feature: Add Divider component to Wave

- src/components/PhoneInput/components/SingleValue.tsx
**What:**
This PR sets `max-width` to `100%` for the `SingleValue` component
​
**Why:**
Fixes issue #242 
​
**How:**
​
**Media:**
**Checklist:**
> fix: giving singlevalue full max width to override the selectlist styles

- src/essentials/Colors/docs/SemanticColorsTable.tsx
**What:**
Fix a bug where the semantic colors where not appearing in the table in the docs.
​
**Why:**
We want to deprecate "regular old colors" in favour of semantic colors, therefore we should offer the best possible experience to our users when working with the latter.
[Check out how the colors do not appear in the table in our docs](https://wave.free-now.com/essentials/colors#functional-reference)
​
**How:**
- Properly converting a `Map` with all of the colors to an `Array` in order to iterate and `.filter` it on the table.
​
**Media:**
Before
After
**Checklist:**
> fix: display semantic colors in table and allow to filter them

- src/components/Popover/Popover.tsx
- src/components/Popover/PopoverContent.tsx
- src/components/Popover/docs/Popover.mdx
**What:**
Expose padding prop for Popover component
​
**Why:**
When integrating the Popover feature, the **padding** prop has not been exposed from parent component, and thus would always fall to default value (**1rem**)... 
However, we now have use-cases where we need to remove this additional default padding - use no padding on Popover content.
e.g. (DropdownMenu)
**How:**
- exposed the padding prop on Popover component and kept default value of 1rem
- added example for Popover with no padding on the documentation page
> style(popover): expose padding prop for Popover component

- src/components/Popover/Popover.tsx
- src/components/Popover/PopoverContent.tsx
- src/components/Popover/docs/Popover.mdx
**What:**
Expose padding prop for Popover component
​
**Why:**
When integrating the Popover feature, the **padding** prop has not been exposed from parent component, and thus would always fall to default value (**1rem**)... 
However, we now have use-cases where we need to remove this additional default padding - use no padding on Popover content.
e.g. (DropdownMenu)
**How:**
- exposed the padding prop on Popover component and kept default value of 1rem
- added example for Popover with no padding on the documentation page
> fix: expose padding prop and adjust z-index for Popover component

- fixtures/typescript-build/src/index.tsx
- src/components/PhoneInput/PhoneInput.tsx
- src/components/PhoneInput/docs/PhoneInput.mdx
- src/components/PhoneInput/docs/PhoneInputPropsTable.tsx
- src/docs/PropsTable.tsx
Allows to attach portals and exposes implementation level APIs
​
**Why:**
Closes #256 #259
​
**How:**
- adds `listPortalTarget` prop to be able to attach the prefixes popup to another HTML element
- adds `inputProps` and `selectListProps` props and passes them to the corresponding components. Those props has less priority than higher level props of the `PhoneInput` (e.g. `<PhoneInput id='hello' inputProps={{id: 'input'}} />` will use _hello_ as the id)
- updated the documentation
​
**Checklist:**
> Expand PhoneInput API

- CODEOWNERS
- docs/changelog.mdx
- fixtures/typescript-build/src/index.tsx
- package-lock.json
- package.json
- src/components/PhoneInput/PhoneInput.tsx
- src/components/PhoneInput/docs/PhoneInput.mdx
- src/components/PhoneInput/docs/PhoneInputPropsTable.tsx
- src/components/Popover/Popover.tsx
- src/components/Popover/PopoverContent.tsx
- src/components/Popover/docs/Popover.mdx
- src/components/Table/docs/Table.mdx
- src/docs/PropsTable.tsx
- src/essentials/Colors/docs/SemanticColorsTable.tsx
**What:**
​
**Why:**
​
**How:**
​
**Media:**
**Checklist:**
> merging main with the prop branch

- src/components/Accordion/Accordion.tsx
- src/components/Accordion/components/ChevronDown.tsx
- src/components/Accordion/components/ChevronUp.tsx
- src/components/Accordion/components/Compact.tsx
- src/components/Accordion/components/Default.tsx
- src/components/Accordion/components/Header.tsx
- src/components/Banner/Banner.spec.tsx
- src/components/Banner/Banner.tsx
- src/components/Box/Box.spec.tsx
- src/components/Button/Button.spec.tsx
- src/components/Toggle/Slide.tsx
- src/components/Tooltip/Tooltip.tsx
- src/essentials/index.ts
**What:**
Start migrating components to use semantic colors.
​
**Why:**
Part of #203 
​
**How:**
Use `SemanticColors` instead of `Colors`in:
- Accordion
- Banner
- Box
- Button
- Toggle
- Tooltip
> refactor: migrate first 5 components to SemanticColors

- src/components/Password/ToggleButton.ts
Some browsers lack support for `end` value for `align-items` css prop.
This would make the icon in ToggleButton to be misplaced.
More specifically:
https://caniuse.com/mdn-css_properties_align-items_flex_context_start_end
Close issue #290
​
**Media:**
Before:
After:
**Checklist:**
> fix(password): use `flex-end` instead of `end`

- src/components/Input/InnerInput.tsx
- src/components/Input/InputProps.ts
- src/components/Input/docs/Input.mdx
**What:**
Fixes #296
​
**How:**
Adds checks of the HTML input value via `useRef`
> Fixes uncontrolled input's label position

- package-lock.json
- package.json
- src/components/Datepicker/Month.tsx
- src/index.ts
- src/polyfills.ts
- src/utils/__mocks__/ids.ts
- src/utils/ids.ts
**What:**
Remove remaining use of `nanoid` in the project.
​
**Why:**
To get rid of the dependency.
​
**How:**
- Stop using `generateId` in `Month.tsx`
- Delete the `generateId` util (`ids.ts`)
- Delete `ids.ts` mock
- Delete `polyfills.ts` file, which was used only for `nanoid`
​
**Checklist:**
Part of #311 
Closes #240
> Wech 28/remove nanoid

- src/components/InfoBanner/InfoBanner.tsx
- src/components/InfoBanner/blocks/InfoBannerCard.tsx
- src/components/InfoBanner/docs/InfoBanner.mdx
- src/components/index.ts
**What:**
Implementing the compound components approach for building out the InfoBanner component (with multiple links as required for one of our products atm)
​
**Why:**
Explanation & Discussion: https://github.com/freenowtech/wave/issues/335
**How:**
- Create building blocks for InfoBanner: InfoBannerCard wrapper + blocks: Title, Description, LinkList (with defined spacing), Link
- Keeping the original component as is
**Media:**
**Extra**
Added some temporary documentation, will document properly on Storybook after migration is complete, as this will go directly to **main** before migration.
**Checklist:**
> feat: implement compound component approach for InfoBanner

- src/components/Password/Password.tsx
**What:**
Fixed set focus on password input while use click on eye button.
​
**Why:**
Improving the user experience, Closes #124 
​
**How:**
Added the focus based on input id.
​
**Checklist:**
> fix: set focus on password input resolve #124

- src/components/Label/Label.tsx
**What:**
Add support for children props inside Label component.
​
**Why:**
When using the Label component, the console shows following error:
```Type '{ children: string; }' has no properties in common with type 'IntrinsicAttributes & LabelProps'.```
​
**How:**
Extend the LabelProps with ```ComponentPropsWithoutRef<'span'>```
> fix: add support for children props inside Label component

- src/components/Grid/Grid.tsx
**What:**
Add missing `children` prop type definition to `Row` component.
Fixes #345.
**Why:**
`children` prop type was not supported for `Row` component.
​
**How:**
Extending component props with `PropsWithChildren`.
​
**Media:**
N/A
**Checklist:**
> fix: support children prop type in row component

- src/components/Tooltip/Tooltip.tsx
**What:**
In this PR we're adding a new prop `container` to the `Tooltip` component where the tooltip should be rendered into.
​
**Why:**
This PR closes #349.
Tooltips that are rendered in Modal dialogs can cause scrollbars to appear. It was not like that in previous version of wave (1.15.1).
**How:**
* Introduce new (optional) prop `container` to Tooltip component where the tooltip body should be rendered into
* Render the tooltip body into `container` via react portal
* See [internal discussion](https://mytaxi.slack.com/archives/CLM50RECU/p1690799683872489) 
* Implementation according to [popper library documentation](https://popper.js.org/react-popper/v2/react-portals/) 
​
**Media:**
Before:
After:
**Checklist:**
> Render Tooltip via React Portal

- src/components/Breadcrumbs/Breadcrumbs.spec.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/Breadcrumbs/docs/Breadcrumbs.stories.tsx
- src/components/Breadcrumbs/docs/Breadcrumbs.storybook.mdx
- src/components/Breadcrumbs/docs/DefaultBreadcrumbs.tsx
**What:**
​
**Why:**
Add new component Breadcrumbs
​
**How:**
Created new component
Added documentation
Wrote tests
**Media:**
Issue:  #324
> feat: add breadcrumbs component

- .storybook/preview-head.html
- src/components/SelectList/SelectList.spec.tsx
- src/components/SelectList/SelectList.tsx
- src/components/SelectList/docs/SelectList.stories.tsx
- src/components/Tag/Tag.spec.tsx
- src/components/Tag/Tag.tsx
- src/components/Tag/__snapshots__/Tag.spec.tsx.snap
**What:**
Error Variant for Tag and SelectList Options (#354).
​
**Why:**
We want to highlight certain items to make it clear to the users that those are invalid and they should remove them. Otherwise the configuration will be considered broken.
​
**How:**
- Fix missing Open Sans font in storybook
- Add storybook stories for SelectList with multi select
- Support new `variant = "default" | "disabled" | "error"` property in the Tag component
- Support having "error" property on options of SelectList element to render the entry tag in "error" variant
- Use semantic colors in accordance with design specification for tags in Tag and SelectList
​
**Media:**
Tag:
SelectList:
**Checklist:**
> Add variants of tag component in Tag and SelectList

- src/components/FilePicker/FilePicker.tsx
- src/components/Modal/docs/ModalCreator.tsx
- src/components/Pagination/docs/PaginationProvider.tsx
- src/components/Table/docs/ComplexDataTable.tsx
- src/components/Table/docs/DefaultTable.tsx
- src/components/Table/docs/SkeletonTable.tsx
- src/essentials/Spaces/docs/SpacesContainer.tsx
**What:**
Replace the deprecated `weak` prop in favour of `secondary` in internal usages of the `Text` component
​
**Why:**
The `weak` prop is deprecated so we shouldn't use it, on top of that using it throws a warning which bubbles up to external projects that use Wave components with usages of `weak`
​
**How:**
Replace all usages of `weak` prop of `Text` components
**Checklist:**
Closes #304
> refactor: replace deprecated weak prop for secondary in text usages

- src/components/Input/InnerInput.tsx
- src/components/Input/__snapshots__/Input.spec.tsx.snap
**What:**
In this PR we are adding `aria-invalid` to the `Input` component if there is an error
​
**Why:**
​This is for better accessibility, currently we can only assert if an input box contains an error through CSS computations, which is not the best practice
**How:**
Add `aria-invalid` if `error` exists
​
**Media:**
**Checklist:**
> feat: adding aria-invalid when an input has an error for accessibility

- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/SelectList/SelectList.spec.tsx
- src/components/SelectList/SelectList.tsx
- src/components/Tag/Tag.spec.tsx
- src/components/Tag/Tag.tsx
**What:**
Migrate new `Breadcrumbs` component to use css vars for colors.
​
**Why:**
The `Breadcrumbs` component has been implemented in `main`, where our css variables are not yet available, we want to migrate it to use them so that when Wave 2.0 gets released it's using our new css variables.
​
**How:**
I've migrated all color values in `Breadcrumbs` so they are using `getSemanticValue`. Please review the semantic values that I've chosen and let me know how to improve them, I'm not convinced by the inverted colors 🙏🏽 
​
**Media:**
**Checklist:**
Closes #361
> feat(breadcrumbs): use css variables for colors

- .github/workflows/library.yml
**What:**
Stop autopublishing in `next` branch
​
**Why:**
We've had autopublishing enabled in `next` for a long time but many releases were actually skipped (not published) due to failed jobs in the pipeline. Apart from that there was an incident last Friday (29/09) where a v3 prerelease was published by mistake. Since it brings more issues than help we should disable it for now, we can always enable it back in the future.
​
**How:**
- Remove `next` branch in `release` job of `library.yml` workflow file
​
**Media:**
**Checklist:**
> ci: disable semantic-release autopublishing in next

- src/codemods/__tests__/block-to-width-100-test.ts
- src/codemods/__tests__/colors-to-css-vars-test.ts
- src/codemods/__tests__/deprecated-icons-test.ts
- src/codemods/__tests__/tooltip-placement-test.ts
- src/codemods/__tests__/weak-to-secondary-test.ts
**What:**
Use ES modules in codemods tests instead of CommonJS
​
**Why:**
The codemods tests were using CommonJS modules without any export, if I'm not wrong this makes the file not act as a module but as part of the global scope, since we had the same import in each file to test `jscodeshift` codemods they ended up conflicting with one another (see media section).
​
**How:**
- Replace `require` for `import` in each codemod test file
​
**Media:**
The issue: 
You can check the entire [job log](https://github.com/freenowtech/wave/actions/runs/6378675053/job/17309726510?pr=383) if you prefer
**Checklist:**
> test: use ES modules in codemods tests

- .prettierignore
**What:**
Makes prettier ignore codemods fixtures
​
**Why:**
For each codemod test there are 2 fixture files, an `*.input.tsx` and an `*.output.tsx`, the test executes the codemod against the input file and compares the result with the output file, it only succeeds when they match. Since codemods are not expected to format the result code for you (since every project has different code styles) in case we format the input or the output files they could stop matching and provoke a failing test.
​
**How:**
- Add the path to the codemods fixtures in `.prettierignore`
​
**Checklist:**
> Make prettier ignore codemods fixtures

- src/components/Breadcrumbs/Breadcrumbs.tsx
enhance breadcrumbs style:
- nowrap when is longer than the container
- accept margin props
- scroll right if it's longer than the container
​
The design was not ideal breaking every word and going to a new line.
​
- adjust the style of the `ul` and `li`s
- use the ref to change the scroll
​
**Before** 
**After** 
<video width="347" alt="Screenshot 2023-10-10 at 16 48 17" src="https://github.com/freenowtech/wave/assets/12762609/553615a5-98f4-4fc4-9106-e7e7f1c44623">
> fix: enhanced breadcrumbs style

- src/components/Datepicker/Datepicker.tsx
- src/components/Datepicker/DatepickerRangeInput.tsx
- src/components/Datepicker/DatepickerSingleInput.tsx
- src/components/Input/InnerInput.tsx
- src/components/Input/Input.tsx
- src/components/Password/Password.tsx
- src/components/PhoneInput/PhoneInput.tsx
**What:**
Make refs point to the most obvious element in `Input` and `Password` components and correct refs usages in our components. Apart from that I've also removed the `forwardRef` from our internal `Datepicker` component since it wasn't being used (this is not a component exposed by Wave, it's used internally by `DatepickerSingleInput` and `DatepickerRangeInput`)
​
**Why:**
To correct our usages of refs so that it follows [our agreement](https://github.com/freenowtech/wave/issues/156#issuecomment-880546292).
​
**How:**
- Correct ref type in `Input`, `Password` and `InnerInput` to `HTMLInputElement`
- Correct the ref in `InnerInput` so it's passed to the input instead of to the wrapper
- Adapt `DatepickerRangeInput` to use the new `Input` ref
- Adapt `PhoneInput` to use the new …
> Correct forwarded refs

- src/components/InfoBanner/blocks/InfoBannerCard.tsx
**What:**
Allow to overwrite the `attrs` set in `InfoBanner` compound component (`InfoBannerCard`)
​
**Why:**
With the compound approach we want to bring to our users freedom to compose their own version of our components, therefore we should allow them to overwrite our preset attributes.
​
**How:**
Overwrite attributes in `.attrs` with the passed props in all `InfoBannerCard` blocks
**Explanation**
In styled-components the precedence of passed "attributes" to a component is [`attrs` > `props` > `defaultProps`](https://github.com/styled-components/styled-components/issues/2372#issuecomment-570291654), meaning that `attrs` overwrites everything.
Before we had our `InfoBannerCard.Link` as
```tsx
const StyledLink = styled(WaveLink).attrs({ fontSize: 0, textAlign: 'left', target: '_blank', …
```
> fix: allow to overwrite attrs in InfoBannerCard

- docs/migrating.storybook.mdx
- package.json
- scripts/run_v2_migration.sh
Closes #399
Allows users to run all codemods with a command `npx @freenow/wave run_v2_migration src/**/*`
​
I made several attempts, but the leaner one is to have a proxy Bash script that passes all provided arguments to the jscodeshift CLI. 
It scans the _codemods_ folder and executes the jscodeshift with every transformation function. If we add more migrations, they will be executed together with old.
​
> Execute all codemodes using one command

- docs/migrating.storybook.mdx
- src/components/Text/docs/Text.storybook.mdx
Describes that `Text` now inherits the colour of the container.
I observed how other engineers migrated to Wave 2.0 and noticed they were surprised by this behaviour. I think it is worth highlighting in the migration guide
​
> Describes the new `Text` component behaviour

- src/essentials/Colors/Colors.ts
- src/essentials/Colors/ModernColors.ts
- src/essentials/Colors/docs/SemanticColorsTable.tsx
- Fixes a bug in our docs where the hsl values in the semantic colors table were not being refreshed when the light/dark theme changed.
- Make the colors table show the current scheme and the inverted scheme colors at the same time
https://github.com/freenowtech/wave/assets/46452321/be895b10-1495-4b08-8c45-225520405034
To have the correct hsl values for dark schema colors.
- Point to light/dark schema object based on the colors scheme the user is viewing
- Reorder light/dark schema colors object so the order of the colors matches (so that the table order is consistent for both schemas)
- Add a column in the `CssVariablesTable` for the inverted scheme color
- Remove the `Hex Color` column in `CssVariablesTable`
Closes #419
> docs: fix semantic colors hsl values in colors table

- .github/workflows/docs.yml
- .github/workflows/library.yml
Bump Github Actions versions to latest major
Warnings in our existing pipelines
Node 16 has reached end of life, [Github is transitioning all Actions to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).
- Update all actions we are using to the latest major
`actions-gh-pages` (used to deploy the documentation site) hasn't yet updated to Node 20, [once it does](https://github.com/peaceiris/actions-gh-pages/issues/1062) we can migrate it as well
> ci: bump action versions to latest major

- src/components/Datepicker/Datepicker.tsx
- src/components/Datepicker/DatepickerContentElements.tsx
- src/components/Datepicker/DatepickerSingleInput.tsx
- src/components/Datepicker/docs/DatepickerOnModal.tsx
- src/components/Input/InnerInput.tsx
- Fixes Datepicker elevation when appearing on a Modal
- Fixes Datepicker props not extending Input props
- Fixes "bottom-lined" Input variant ref
Before (Datepicker underneath Modal)
After (Datepicker on top of Modal)
To offer a consistent experience on the Datepicker and Input components
- Move z-index to the highest Datepicker container (before it was in a lower level container and the Modal would take preference)
- Extend `InputProps` in `DatepickerSingleInputProps` since props are being sent to trigger `Input`
- Point ref in `InnerInput` with "bottom-lined" variant to the actual html `input` instead of the the wrapper `div`
- Minor addition of a label for the "Datepicker on Modal" story
Closes #421
> Fix datepicker elevation, props and bottom-lined input ref

- src/components/Datepicker/Datepicker.tsx
- src/components/Datepicker/DatepickerContentElements.tsx
- src/components/Datepicker/DatepickerRangeInput.tsx
- src/components/Datepicker/DatepickerSingleInput.tsx
- src/components/Datepicker/docs/DatepickerOnModal.tsx
- src/components/Input/InnerInput.tsx
- src/components/Tooltip/Tooltip.tsx
- src/utils/hooks/useClosestColorScheme.ts
- src/utils/hooks/useMutationObserver.ts
Fixes a bug where enforced color schemes would not get applied to components in Portals (Datepickers and Tooltip)
Light scheme is enforced to Datepicker but only gets applied to the trigger input, the actual Datepicker is still dark
Corrected behaviour
If a user wants to enforce a color scheme to a component it should get applied to the whole component, not just part of it
- Create a utility hook `useClosestColorScheme` that finds the enforced color scheme closest to the passed element
- Wrap portal content in `LigthScheme`/`DarkScheme`/`React.Fragment` based on the result of `useClosestColorScheme` passing the trigger element (e.g. the input that renders the Datepicker when you click on it), this is done for both Datepickers as well as Tooltip (all components that use portals)
Closes …
> Fix applied color scheme on portals

- src/components/Modal/docs/Modal.stories.tsx
- src/components/Offcanvas/Offcanvas.tsx
- src/components/Offcanvas/docs/Offcanvas.stories.tsx
- src/components/Offcanvas/docs/Offcanvas.storybook.mdx
- src/components/index.ts
Fixes an issue where the `useOffcanvasDismiss` hook was not being exported. Fixes issues with scrolling in the docs
Check out in our docs how scrolling is not possible for the [Offcanvas](https://wave.free-now.com/?path=/docs/components-offcanvas--docs) and [Modal](http://localhost:6006/?path=/docs/components-modal--docs) docs
​
Modal scrolling now
https://github.com/freenowtech/wave/assets/46452321/03475132-00e9-45df-baaa-ea0eb79e87d3
Offcanvas scrolling now
https://github.com/freenowtech/wave/assets/46452321/00e4e291-bbea-41d3-b03f-30b43f59b2fd
We need to export `useOffcanvasDismiss` to be able to dismiss the `Offcanvas` through a hook
We should be able to scroll in our docs site 😅 
​
- Export `useOffcanvasDismiss` in the components index
- Removed `defaultProps` in `Offcanvas` in …
> fix(offcanvas): export offcanvas hook

- docs/get-started.storybook.mdx
Document how to get rid of prop filtering warnings in the `Get started` section
​
So users of Wave can easily understand how to avoid undesired props being filtered to the DOM and React emitting warnings about it
- Add an explanation of how to use `StyleSheetManager` in the get started section
Relates to #388
> docs: document recommendation to get rid of prop filtering warnings

- src/components/Tooltip/Tooltip.tsx
Fixing Tooltip light mode/dark mode appearance.
​
It was ugly and hideous (aka eyes bleeding on light mode and Tooltip unreadable when in dark mode)
​
Added color for tooltip color and removed InvertedColorScheme wrapper for Tooltip.
> tooltip content colors

- src/components/TabBar/TabBar.tsx
Make Wave's theme apply to `TabBar` component
```tsx
{/* When passing a margin to TabBar it doesn't apply it correctly */}
{/* mb={3} should equal 24px (Spaces[3]), it is 16px instead */}
<TabBar mb={3}>
{['Tab One', 'Tab Two'].map(it => (
<TabBar.Link
key={it}
href="#"
onClick={e => {
e.preventDefault();
setSelected(it);
}}
selected={selected === it}
>
{it}
</TabBar.Link>
))}
</TabBar>
{/* Here's a correct margin for comparison */}
<Box width='100%' mb={3} >The margin above is 16px, but should be 24px</Box>
<Box width='100%' >The margin above is 24px</Box>
```
Check it out in this [CodeSandbox](https://codesandbox.io/p/sandbox/wave-tabbar-margin-bug-tgl46v?file=%2Fsrc%2FApp.tsx%3A30%2C16)
All Wave components should have Wave's theme applied to them
​
- Pass our `theme` as a styled …
> fix(tabbar): make Wave's theme apply to TabBar component

- src/components/Search/Search.tsx
Make `SearchProps` extend the `InputProps` and spread its props into the `StyledInput` of the `Search` component.
No UI change.
Search missed a few `InputProps` to it's `StyledInput`; the one missing that we currently wanted to use is `autoFocus` so that we can have the user automatically focus in the SearchInput with a single attribute.
Making `SearchProps extend InputProps` (omitting results because of conflict) and removing a few props from `SearchProps` (disabled, placeholder, size) as they are already in `InputProps`
> fix: extends InputProps on search and spread into search SyledInput

- src/components/ColorScheme/EnforcedColorScheme.tsx
- src/components/SelectList/SelectList.tsx
Fixing the problem from Issue #434 
https://www.loom.com/share/a76665438d7745adb3abeb1cf962e7b6?sid=73419f0a-b715-4d97-afa9-e3fc575b82d3
- Use `useClosestColorScheme` to identify if enforced color scheme is applied
- Wrap the `Menu` component from `react-windowed-select` with respective color scheme component
> fix(SelectList): overwrite styling with enforced color scheme for menu

- src/components/Pagination/Pagination.tsx
Fixes the size of the Page Size selector by removing the width attribute sent to it.
Page size selector with not broken size:
Responsiveness of boxes:
https://github.com/freenowtech/wave/assets/153822795/bbe228e3-1486-4cf0-b930-c01bd44a4d45
There is a bug where the page size selector is too small and does not fully display the number of the selected page size. By removing the set `width="4.5em"` it displays the selected page size correctly.
Adds 3 boxes inside of ButtonsContainers, with the left (PageSize selector) and right (empty) having `flex='1'` so that they take the necessary space, and having the box with the pagination navigation in the middle.
Sets the container inside of the first flexable box with `minWidth='5em'` and `width="fit-content"` so that the PageSize selector can't be …
> fix: remove width from pageSize selectList box

- src/components/Datepicker/index.ts
- src/components/Table/index.ts
Adds missing type exports on the `Table` and and `Datepicker` components
We were missing types in some projects and had imports like 
`​import type { DateRange } from '@freenow/wave/lib/types/components/Datepicker/DatepickerRangeInput'`
- Export `DateRange` from `src/components/Datepicker/index.ts``
- Export `SortingDirection` from `src/components/Table/index.ts`
> fix: add missing type exports

- src/components/index.ts
Add missing type exports in components index files
N/A
In #445 I added missing type exports to the `Table` and `Datepicker` components index files, but I was missing those exports in the `/components/index.ts` file 🙈
​
- Export `DateRange` and `SortingDirection` from ' /components/index`
> fix: add missing type exports in components index

- src/essentials/Colors/Colors.ts
- src/essentials/Colors/ModernColors.ts
- src/essentials/Colors/types.ts
Add new semantic colors for charts.
(+ fix few existing primary colors in modern look)
Modern
Classic
We need those colors in Admin Panel for a histogram component.
​
Add new primary colors and introduce new semantic colors for `chart`.
> feat: add semantic colors for chart (#448)

- src/components/Checkbox/components/Checkmark.tsx
- src/components/Checkbox/docs/Checkbox.stories.tsx
Fix the low contrast ratio on selected disabled checkbox
[453](https://github.com/freenowtech/wave/issues/453)
Closes #453 ​
Use `background-element-disabled-default` instead of `background-element-disabled-faded`
> fix: adjust contrast ratio on selected disabled checkbox

- src/essentials/Colors/Colors.ts
- src/essentials/Colors/ModernColors.ts
- src/essentials/Colors/types.ts
Our designer asked us to add two new neutral base colors to the modern theme and add new semantic colors while deprecating others.
We are redefining the background and surface tokens and will need these extra tones. (neutral-10, neutral-800)
- Add new colors and correct the existing neutral colors (some they were slightly off but it's not significant so should't be considered a breaking change).
- Add new semantic color `background-page-elevation-0`
- Change color for `background-page-default` slightly
> feat: add two new neutral colors and map them to new semantic color

- docs/migrating.storybook.mdx
- src/components/ColorScheme/docs/DarkScheme.stories.tsx
- src/components/ColorScheme/docs/DarkScheme.storybook.mdx
- src/index.ts
- src/utils/enforceSchemeOnElement.ts
- src/utils/index.ts
Adds an `enforceSchemeOnElement` util to enforce a color scheme on a passed element
Part of migration docs
Color scheme docs
Most projects migrating to Wave 2 are enforcing the light color scheme because they are not yet prepared for the dark scheme, they do that by wrapping their app with a `LightScheme` component (as stated in our previous docs). The issue there is that the `LightScheme` will be rendered below the HTML `body`, so the background and color of the `body` will still follow the user OS preferences, instead of the manual override by the developer.
- Add `enforceSchemeOnElement` util
- Adapt migration docs to use the new util when the dev wants to enforce a color scheme
- Add docs about the util in the color scheme docs
> feat: add util to enforce a color scheme on an html element

- .github/ISSUE_TEMPLATE/bug_report.md
- CODEOWNERS
- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
* Update several parts of the docs and codeowners/maintainers.
* Added a notice about the Color Scheme in the install instructions (Wave >2.x now doesn't work out-of-the-box without it).
* Replace the code sandbox provided in the bug report template, to a new one made with StackBlitz, in order to use Vite as the build tool, and with latest version of Wave.
[README](https://github.com/freenowtech/wave/blob/ad0fded287e766c9d3f8bb571f6f60ad0c9ce1fd/README.md)
[CONTRIBUTING](https://github.com/freenowtech/wave/blob/ad0fded287e766c9d3f8bb571f6f60ad0c9ce1fd/CONTRIBUTING.md)
[MAINTAINERS](https://github.com/freenowtech/wave/blob/ad0fded287e766c9d3f8bb571f6f60ad0c9ce1fd/MAINTAINERS.md)
​
> docs: update maintainers, codeowners, codesandbox, readme

- .storybook/preview-head.html
- .storybook/preview.tsx
- package-lock.json
- package.json
- src/components/experimental/Button/Button.tsx
- src/components/experimental/Button/docs/Button.stories.tsx
- src/components/experimental/Chip/Chip.tsx
- src/components/experimental/Input/Input.tsx
- src/components/experimental/Text/Text.tsx
- src/components/experimental/Text/docs/Text.stories.tsx
- src/essentials/experimental/theme.ts
Button: Added all possible button states
Typography: Added loading the variable font and supported variable font-width
<table>
<tr>
<td>
<b>before</b>
</td>
<td>
<b>after</b>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
​Resolves [DISP-140](https://jira.intapps.it/browse/DISP-140)
> Disp 140/button

- package.json
- src/essentials/experimental/index.ts
- src/essentials/experimental/theme.ts
- src/experimental/index.ts
- src/index.ts
Adds exports for the `experimental` folder, so that when distributing the package it can be accessed directly.
Now the experimental components can be accessed like:
```typescript
import { Button, Chip } from '@freenow/wave/experimental'
``` 
To allow to directly access experimental features, without needing to know the internal file structure of the package.
- Adds [exports](https://nodejs.org/api/packages.html#exports) field in package.json to define the default + the experimental exports
- Adds `typesVersions` field to package.json to override the `experimental` types (so they don't come from the main index.d.ts file)
I'm opening this as a draft PR because the experimental components are not ready to be distributed yet, once we have a first experimental component we can merge this.
I've …
> feat: add exports for experimental components

- src/components/experimental/Label/Label.tsx
- src/components/experimental/Label/docs/Label.stories.tsx
- src/essentials/experimental/cssVariables.ts
- src/essentials/experimental/globalStyles.ts
- src/essentials/experimental/index.ts
Adds a Label component
​<img width="402" alt="Screenshot 2024-09-19 at 17 55 02" src="https://github.com/user-attachments/assets/61b67616-e27d-4ae4-a5dd-ecbcc209c7cd">
​Closes DISP-142
As labels will often be customized on the project level and will use bare colors instead of semantic ones, I've added a `darkTheme` helper to simplify writing the css (see the `Custom` story for example usage)
> feat(label): add experimental label component

- src/components/experimental/ComboBox/ComboBox.tsx
- src/components/experimental/Select/Select.tsx
Fixes displaying overflowing content in Combobox' and Select' popovers
​<img width="328" alt="Screenshot 2024-10-15 at 13 26 55" src="https://github.com/user-attachments/assets/3db56923-4096-454b-8f7a-49c9a0618114">
> fix: fix overflow in popover

- src/components/experimental/Divider/Divider.spec.tsx
- src/components/experimental/Divider/Divider.tsx
- src/components/experimental/Divider/docs/Divider.stories.tsx
- src/essentials/experimental/Colors.ts
- src/essentials/experimental/types.ts
This PR adds a divider component to the experimental components list
​
DISP-144
​
* Reuse the same API as the existing `Divider`
* Add a new experimental semantic token `divider` for the colours
> feat: adding an experimental divider component

- src/components/experimental/Button/Button.tsx
I noticed that we are showing the cursor for disabled buttons. This MR fixes it
It can be confusing to the user to show a cursor when the button is not clickable
​
* CSS
> fix: changing the cursor pointer for disabled states

- src/components/experimental/ComboBox/ComboBox.tsx
- src/components/experimental/IconButton/IconButton.tsx
- src/components/experimental/ListBox/ListBox.tsx
- src/components/experimental/Popover/Popover.tsx
- src/components/experimental/Select/Select.tsx
1. Moves the "width = trigger-width" styling into the popover
2. When a listbox item has a `href` it's rendered as an `a`, which is a phrasing content by default
​
​Illustrates both issues
https://jira.intapps.it/browse/DISP-316
> fix: popover and listboxitem styling

- .storybook/preview.tsx
- .stylelintrc
- src/components/experimental/Backdrop/Backdrop.tsx
- src/components/experimental/Dialog/Dialog.tsx
- src/components/experimental/Dialog/docs/Dialog.stories.tsx
- src/components/experimental/Modal/Modal.tsx
- src/components/experimental/Text/Text.tsx
- src/components/experimental/index.ts
Adds an experimental Dialog Component using the new Modal & Backdrop components. I decided to not re-export them as public yet
​
​https://jira.intapps.it/browse/DISP-331
> feat(dialog): add experimental dialog

- src/components/experimental/Button/Button.tsx
Adds `justify-content` prop with value `center` in the experimental `Button` component
Before:
https://github.com/user-attachments/assets/cff3b0c0-04f3-4235-bc97-2a04ce766e53
After:
https://github.com/user-attachments/assets/d5b67378-049b-49cc-ad2b-c272a5ee1f0c
​
> fix: center content in experimental button

- src/components/experimental/Select/Select.tsx
- src/components/experimental/Select/docs/Select.stories.tsx
Adds customisation ability for the Select value
Normally, select works like WYSIWYG: the user selects an item in the list and it is displayed as a select value
​Scenario: we might show additional information in the list (Fleet label + fare + ETA), but still want to display only the label as the value, when the item is selected
Introducing the `renderValue` prop
> feat(select): add value customisation

- .stylelintrc
- src/components/experimental/Table/Table.tsx
- src/components/experimental/Table/docs/Table.stories.tsx
- src/components/experimental/index.ts
Adds an experimental table component (a styled version of [React Aria Table](https://react-spectrum.adobe.com/react-aria/Table.html))
​
> feat(table): add experimental component

- src/components/experimental/IconButton/IconButton.tsx
Spread `restProps` into the button element so it receives additional properties such as `arial-label`
The experimental icon button is not handling needed properties such as `aria-label`
​
> fix: pass rest props to the icon button container

- src/components/experimental/Snackbar/Snackbar.tsx
Add support for passing a ref to the component
Better integration with parent components and libraries that rely on refs.
> fix: add ref support to snackbar

- src/components/experimental/IconButton/IconButton.tsx
- src/components/experimental/Snackbar/Snackbar.tsx
This PR removes the overriding of the `onPress` prop when extending the interface for the `IconButton` component.
It also adds the correct event typing in `Snackbar`
This override we are removing causes us to lose the event typing inherited from `AriaButtonProps`
> fix: remove prop type overriding and add event type in snackbar

- src/components/experimental/Table/Table.tsx
Otherwise ::before covers everything
> fix(table): add non-static position to all the cell content

- src/components/experimental/Button/Button.tsx
Preserves button width during loading state by wrapping children and spinner in separate containers, hiding children with opacity and visibility
https://github.com/user-attachments/assets/11f3e29a-f4d2-49ff-b3f9-651cacea467c
https://github.com/user-attachments/assets/1c3f1562-bca3-41c4-86d0-7bd832c5e3ff
Improves the layout consistency
> fix: preserve button content to maintain consistent width during loading state

- src/components/experimental/ComboBox/ComboBox.spec.tsx
- src/components/experimental/ComboBox/ComboBox.tsx
- src/components/experimental/ComboBox/docs/ComboBox.stories.tsx
- src/utils/hooks/useMergeRefs.ts
This PR adds support for an external `ref` in the `ComboBox` component, enabling parent components to pass their own refs for access to the input element within the `ComboBoxInput` 
https://github.com/user-attachments/assets/18122ae2-ffbf-48ca-b317-5dbd1fa4db18
So we can programmatically focus or interact with the input field within the `ComboBox`
​
A requirement of UI improvement SUP-45087
> feat(combo-box): external input ref support

- src/components/experimental/Divider/Divider.spec.tsx
- src/components/experimental/Divider/Divider.tsx
Fixes Divider margins to 0.5rem instead of 1rem as it was too big.
The only place we are currently using looked like this with 1rem:
With 0.5rem it looks as expected:
> fix: divider margin

- src/components/experimental/Dialog/Dialog.tsx
- src/components/experimental/Modal/Modal.tsx
Remove dapping to make modals appearance customizable on the project level (we do not have general guidelines what modals should look like yet)
> feat(modal): remove padding from ModalCard

- package-lock.json
- src/components/experimental/IconButton/IconButton.spec.tsx
- src/components/experimental/IconButton/IconButton.tsx
- src/components/experimental/Snackbar/Snackbar.spec.tsx
- src/components/experimental/Snackbar/Snackbar.tsx
Adds a required label prop to <IconButton /> that adds a hidden text to the icon button to describe the Icon action.
> fix: add label prop to icon button

- .stylelintrc
- src/components/Accordion/docs/Accordion.stories.tsx
- src/components/Banner/docs/Banner.stories.tsx
- src/components/Breadcrumbs/docs/DefaultBreadcrumbs.tsx
- src/components/ColorScheme/docs/CurrentScheme.tsx
- src/components/Dimming/docs/Dimming.stories.tsx
- src/components/Divider/docs/Divider.stories.tsx
- src/components/FilePicker/docs/FilePicker.stories.tsx
- src/components/Headline/Headline.tsx
- src/components/Modal/docs/Modal.stories.tsx
- src/components/Offcanvas/docs/Offcanvas.stories.tsx
- src/components/Pagination/docs/Pagination.stories.tsx
- src/components/Table/docs/Table.stories.tsx
- src/components/Tooltip/docs/Tooltip.stories.tsx
- src/components/experimental/ComboBox/docs/ComboBox.stories.tsx
- src/components/experimental/DateField/docs/DateField.stories.tsx
- src/components/experimental/Dialog/docs/Dialog.stories.tsx
- src/components/experimental/Divider/docs/Divider.stories.tsx
- src/components/experimental/IconButton/docs/IconButton.stories.tsx
- src/components/experimental/Select/docs/Select.stories.tsx
- src/components/experimental/TextField/docs/TextField.stories.tsx
- src/components/experimental/TimeField/docs/TimeField.stories.tsx
- src/docs/Source.tsx
- src/essentials/Colors/globalStyles.ts
- src/essentials/experimental/Colors.ts
- src/essentials/experimental/globalStyles.ts
This PR addresses and resolves the current warnings we are getting when running our linter
Technical debt
​
It consists of:
- Adding missing type annotations, mostly in stories
- Removing unused imports
- Removing alert from the experimental `IconButton` story in order to comply with the `no-alert` rule
- Fix the `placement` property used in the `Tooltip` story
- Use media query list obtained with `evalColorSchemeQuery` instead of the event's list in `getCurrentScheme`
- This ensures the correct type (MediaQueryList) is passed and reflects the current state
- Replace deprecated rules with their current equivalents in stylelint config
> fix: lint warnings

- src/components/experimental/Search/Search.spec.tsx
- src/components/experimental/Search/Search.styled.ts
- src/components/experimental/Search/Search.tsx
- src/components/experimental/Search/docs/Search.stories.tsx
- src/components/experimental/TextField/TextField.tsx
- src/components/experimental/index.ts
This is an experimental Search component. Additionally, I changed the behavior of the clear button in TextField to be the same of the Search
​
> feat: add search component

- src/components/Checkbox/Checkbox.tsx
- src/components/Checkbox/components/LabelWrapper.tsx
- src/components/Checkbox/docs/Checkbox.stories.tsx
- src/components/RadioButton/RadioButton.tsx
- src/components/RadioButton/components/Checkmark.tsx
- src/components/RadioButton/components/LabelWrapper.tsx
- src/components/Toggle/Label.tsx
- src/components/Toggle/Slide.tsx
- src/components/Toggle/Toggle.tsx
Replaced `margin` with `gap` in Checkbox, RadioButton and Toggle components to improve UI when no label is undefined.
Also slightly changed the default history for the Checkbox similar to other components, made the default label undefined.
Closes #450
> fix: improve spaces when label is not defined (#450)

- src/components/experimental/Checkbox/Checkbox.tsx
- src/components/experimental/Checkbox/components/LabelWrapper.tsx
- src/components/experimental/index.ts
Current import structure generates a circular dependency when exporting the Checkbox component from the experimental index file
> fix: experimental checkbox imports

- src/components/experimental/Button/Button.tsx
When using the experimental `Button` component, the following error is show in the browser terminal:
```
React does not recognize the `isLoading` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isloading` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
The `isLoading` prop is accidentally passed to the `button` element, which is not recognized.
This issue is resolved by utilizing the transient props feature provided by styled-components (https://styled-components.com/docs/api#transient-props).
> fix: avoid isLoading prop on button element

- src/components/experimental/Backdrop/Backdrop.tsx
- src/components/experimental/Dialog/Dialog.spec.tsx
- src/components/experimental/Dialog/Dialog.tsx
- src/components/experimental/Dialog/docs/Dialog.stories.tsx
This PR introduces an optional invisible backdrop mode for the experimental Dialog component
​
To comply to the design specs of the Dispatcher Tool GTC screen
​
Added an isBackdropVisible boolean prop to the Dialog component that when set to false, it renders a transparent backdrop with CSS pointer-events: none to allow interaction with underlying content while maintaining dialog functionality
> feat: add support of non visible backdrop to the experimental Dialog

- src/components/experimental/RadioButton/RadioButton.tsx
- src/components/experimental/RadioButton/docs/RadioButton.stories.tsx
- src/components/experimental/RadioGroup/RadioGroup.styled.ts
- src/components/experimental/RadioGroup/RadioGroup.tsx
- src/components/experimental/RadioGroup/docs/RadioGroup.stories.tsx
- src/components/experimental/index.ts
- src/essentials/experimental/cssVariables.ts
- src/essentials/experimental/globalStyles.ts
Adds experimental RadioButton and RadioGroup components
​
​
Started adding typescale options to CSS variables
> feat: add RadioButton and RadioGroup

- src/components/experimental/Calendar/Calendar.styled.ts
- src/components/experimental/Calendar/Calendar.tsx
- src/components/experimental/Calendar/docs/Calendar.stories.tsx
- src/essentials/experimental/globalStyles.ts
Support range selection and multiple months in view
​
​
> feat(calendar): support multi-month and range selection

- src/components/experimental/Field/InnerWrapper.ts
Removed the CSS `:has()` selector in the `InnerWrapper` component that was incorrectly applying padding even when labels were visually hidden, and the label is required anyways.
The `:has()` selector was detecting the `Label` component even when they were wrapped in `VisuallyHidden`, causing padding to be applied incorrectly. This resulted in unwanted space at the top of components with hidden labels.
We now rely solely on the prop-based conditional styling (`$hideLabel`), which provides more predictable and consistent behavior across all browsers.
​
> fix: remove unreliable :has() selector in InnerWrapper

- src/components/experimental/TimeField/TimeField.tsx
Properly controls top padding in `TimeField` by passing `hideLabel={!label}` to `InnerWrapper`. Padding is now only applied when a label actually exists
> fix: pass hideLabel prop to TimeField InnerWrapper

- jest.config.js
- package-lock.json
- package.json
- src/components/FilePicker/__snapshots__/FilePicker.spec.tsx.snap
- src/components/TabBar/__snapshots__/Link.spec.tsx.snap
- src/essentials/Colors/Colors.ts
- src/essentials/Colors/ModernColors.ts
- src/essentials/Colors/globalStyles.ts
- src/essentials/theme.ts
[SUP-49317](https://jira.prod.free-now.com/browse/SUP-49317)
Upgrading font family and colours in wave 2.0 for brand evolution as per [this](https://www.figma.com/design/ctaHZoIjoQkSYPqyD3w1x9/Wave-DS-2.0?node-id=7093-4231&t=aM7MuFgg1VWe0LZi-0) design document.
> feat: upgrading colours & font in wave 2.0 | SUP-49317

- src/components/MonthPicker/MonthCalender/MonthButton.tsx
- src/components/MonthPicker/MonthCalender/MonthCalender.tsx
- src/components/MonthPicker/MonthPickerContentElements.tsx
- src/components/MonthPicker/MonthRangePicker.tsx
- src/components/MonthPicker/docs/MonthRangePicker.stories.tsx
- src/components/MonthPicker/docs/MonthRangePicker.storybook.mdx
- src/components/MonthPicker/index.ts
- src/components/MonthPicker/utils.ts
closes: [SUP-49728](https://jira.prod.free-now.com/browse/SUP-49728)
https://github.com/user-attachments/assets/45531244-1fdc-4c6c-9b2f-d370c015fd53
> feat: added month range picker
