freenowtech/wave

CODEOWNERS
**What:**
Add myself as CODEOWNER
**Why:**
Allow to set me as a reviewer
=> update for CODEOWNERS file

CONTRIBUTING.md, README.md
**What**
Update with more information on how to contribute on Github
**Why**
There is people willing to contribute that may not be familiarised with the Open source flow to contribute
=> Update README with information for contributions

.github/workflows/PULL_REQUEST_TEMPLATE/pull_request_template.md
**What:**
Add a template for pull requests
**Why:**
Closes #39 
**How:**
Follow some of the approaches at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> Add pull request template

CODEOWNERS
**What:**
Add one of our designers @rafael-sepeda as code owner to be pulled on reviewers list
=> docs(CODEOWNERS): add @rafael-sepeda

.github/workflows/library.yml, package-lock.json, package.json, release.config.js
This PR configures the Github Action to automatically release changes to `main` branch. It also creates an automatic changelog based on the commits in the release.
=> ci: add semantic-release

README.md
This PR adds two badges for the current build status and the latest npm version.
=> chore: add npm version and ci badge

src/components/Table/docs/Table.mdx
Super simple PR, just fixing a typo so that I can copy paste without errors.
=> docs: fixing typo in doc

src/components/index.ts
**What:**
Export the `Offcanvas` component.
​
**Why:**
It was not exported from the main entry file
​
**How:**
Add export in the main `index.js`
=> fix: export Offcanvas component

src/components/SelectList/SelectList.tsx, src/components/SelectList/docs/SelectListPropsTable.tsx, src/utils/hooks/useGeneratedId.ts
**What:**
​This PR associates the label in the `SelectList` component with the `input` element that it contains
**Why:**
​This is to improve accessibility, before this change, there was a label and there was a select dropdown, but both were not tied to each other
**How:**
​1. Generate an ID property
2. Assign that to the dropdown
3. Use that id with `htmlFor` for the label
**Media:**
https://www.loom.com/share/736830f773bb4343a8ee2232d6e067df
**Checklist:**
=> improvement: associating label with input

src/components/Input/docs/Input.mdx
=> Add example with `id` prop to the input

src/gatsby-theme-docz/components/Header/index.js
**What:**
Add the text with a link
**Why:**
It's not possible to get from the docs to the repo​
**How:**
I added a link to the right side of the menu​
**Media:**
**Checklist:**
=> docs: add a link from the documentation to the github repo

src/components/Box/Box.spec.tsx, src/components/Box/Box.tsx, src/components/Box/__snapshots__/Box.spec.tsx.snap, src/components/FilePicker/FilePicker.tsx, src/components/Search/Search.tsx, src/essentials/theme.ts, src/styled.d.ts
**What:**
- Avoid collision of `color` prop
- Add default theme declaration
- Use theme declaration in `Box` component
​
**Why:**
- Fix issue #190 
- Fix another issue where `Box` requires a value for `theme`
**Checklist:**
=> Fix incompatible box props

src/components/Accordion/components/Description.tsx
**What:**
Replaced `weak`​ with `secondary` to remove the deprecation warning in `Accordion `-> `components `-> `Description`
**Why:**
Closes issue #205
​
**How:**
Replaced `weak `with `secondary` in the `Text `component of Description
​
**Checklist:**
=> replaced weak with secondary since weak was deprecated

src/components/Datepicker/Month.tsx
**What:**
Use generated ids as keys in Datepicker
​
**Why:**
When using the Datepicker component a warning appeared when the Datepicker opened due to multiple keys having the same value in the component that represents each day of the month. Check the screenshots to understand how the keys' values were.
​
**How:**
- Generate an id for each day to ensure that the values are different
​
**Media:**
**Checklist:**
=> Different children with the same key in Datepicker

src/components/Table/docs/Table.mdx
**What:**
I found two small mistakes in Table documentation
=> Updated docs for Table

src/gatsby-theme-docz/components/Header/index.js
**What:**
This PR solves issue #229 
​
**Why:**
The github link and the menu button were overlapping in mobile view, this fixes that
​
**How:**
Moving the menu button inside the container for Github link, adding a `flex` display
​
**Media:**
**Checklist:**
=> improvement: fixing the header UI navigation in mobile view

src/components/Table/components/TableCell.tsx, src/components/Table/components/TableHeaderCell.tsx
**What:**
This PR adds `layout` to the `styled-system` compose function, so that layout props can be applied
​
**Why:**
This fixes issue #224 
​
**How:**
​Add the `layout` function to the `compose` function
**Media:**
Watch me [loom](https://www.loom.com/share/496634167f4849cda3ea8ffc4165cf7a)
**Checklist:**
=> fix: adding layout to the compose styles

README.md
**What:**
Add new contributors and make updates to README's Contributors section
​
**Why:**
Contributors section in our Wave README has not been up-to-date for a while.
​
**How:**
Use **@all-contributors** bot on this PR to add/update your section (like here: [#97](https://github.com/freenowtech/wave/pull/97#issuecomment-854503803))
=> docs: Update Contributors

src/components/Table/docs/Table.mdx
**What:**
​Removing the "experimental" tag from the table documentation
**Why:**
Closes issue #9 
​
**How:**
​Change in documentation file
**Checklist:**
=> fix: removing the experimental label for table, fixes issue#9

src/components/HelperText/docs/HelperText.mdx, src/components/HelperText/docs/HelperTextPropsTable.tsx, src/components/Link/docs/Link.mdx, src/components/Link/docs/LinkPropsTable.tsx, src/components/Tag/docs/DismissableTagPropsTable.tsx, src/components/Tag/docs/Tag.mdx
**What:**
Had to fork out - adding PropsTabla to 3 components docs.
​
**Why:**
Deeps&Chill initiative
**Checklist:**
=> Issue 10 add prop documentation

src/components/FilePicker/FilePicker.tsx
A missing part from: https://github.com/freenowtech/wave/pull/301
=> feat: add alwaysShowActionButton to mobile

src/components/InlineSpinner/InlineSpinner.tsx, src/components/InlineSpinner/__snapshots__/InlineSpinner.spec.tsx.snap
**What:**
- Adds role=progressbar to the component
- Fixes invalid HTML (`div` inside of `span`)
​
**Why:**
Improves accessibility and ​makes targeting of the component in tests easier
**How:**
​
**Media:**
**Checklist:**
=> InlineSpinner fixes

src/components/Tooltip/Tooltip.tsx
**What:**
Fix Tooltips props by typing children explicitly.
​
**Why:**
Close #329
=> fix(tooltip): type children prop

src/essentials/Colors/Colors.ts
Add missing secondary color for border `SemanticColors.boder.secondary`
=> fix: add border secondary

package-lock.json, package.json, src/components/SelectList/SelectList.tsx
Uses my fork of the react-window-select until my PR is merged to the main one
=> Use custom react-windowed-select

docs/index.storybook.mdx
Use `InfoBanner` for the v1 warning/link.
The warning is not very noticeable.
=> docs(v2): use `InfoBanner` for the v1 link

src/components/Datepicker/Datepicker.tsx, src/components/Datepicker/DatepickerContentElements.tsx, src/components/Datepicker/DatepickerRangeInput.tsx, src/components/Datepicker/DatepickerSingleInput.tsx, src/components/Datepicker/docs/DatepickerOnModal.tsx, src/components/Input/InnerInput.tsx, src/components/Tooltip/Tooltip.tsx, src/utils/hooks/useClosestColorScheme.ts, src/utils/hooks/useMutationObserver.ts
Fixes the commit descriptions of the last 2 commits so they follow conventional commits
Since the previous commit messages were wong semantic-release was not triggered, with this PR the intention is to trigger it and release a new library version
Interactively rebasing and changing the commit description so it follows conventional commits
The actual code changes were already reviewed in #425 and #427
=> fix: correct last conventional commits

docs/index.storybook.mdx
=> Fix button alignment on the main page

CODEOWNERS
Add @arturmiglio to codeowners
=> chore: add artur to codeowners

CODEOWNERS
=> Removes Nik from the owners

.storybook/preview-head.html, .storybook/preview.tsx, package.json, src/components/experimental/Text/Text.tsx, src/components/experimental/index.ts, src/essentials/experimental/globalStyles.ts, src/experimental/index.ts, src/utils/experimental/index.ts
- Adds paths to the type declarations
- Adds forgotten export for the experimental Label component
​Fixes [DISP-199](https://jira.intapps.it/browse/DISP-199)
=> fix: exports

src/components/experimental/TextField/ClearButton.tsx, src/components/experimental/TextField/TextField.tsx, src/components/experimental/TextField/docs/TextField.stories.tsx
1. Syncing to the external state is fixed
2. Clearing uncontrolled input is fixed
​
=> fix(text-field): fixes for controlled and uncontrolled states

src/components/experimental/Calendar/Calendar.tsx, src/components/experimental/Calendar/docs/Calendar.stories.tsx, src/components/experimental/TextField/TextField.tsx, src/components/experimental/index.ts
Adds an experimental Calendar component to be used inside of the DatePicker
​
​Closes [DISP-143](https://jira.intapps.it/browse/DISP-143)
=> feat(calendar): add experimental component

.eslintrc.js, src/components/experimental/ComboBox/ComboBox.tsx, src/components/experimental/ComboBox/docs/ComboBox.stories.tsx, src/components/experimental/DatePicker/DatePicker.tsx, src/components/experimental/ListBox/ListBox.tsx, src/components/experimental/ListBox/docs/ListBox.stories.tsx, src/components/experimental/Popover/Popover.tsx, src/components/experimental/Text/Text.tsx, src/components/experimental/TextField/TextField.tsx, src/components/experimental/index.ts, src/essentials/experimental/Colors.ts
​
​
Based on [React Aria](https://react-spectrum.adobe.com/react-aria/ComboBox.html#combobox-1)
=> feat(combo-box): add component

src/components/experimental/Button/Button.spec.tsx, src/components/experimental/Button/Button.tsx, src/components/experimental/Button/docs/Button.stories.tsx, src/components/experimental/IconButton/IconButton.spec.tsx, src/components/experimental/IconButton/IconButton.tsx, src/components/experimental/IconButton/docs/IconButton.stories.tsx
This PR adds the text button variant to the experimental `Button` component. It also adds the loading state for both the `Button` and `IconButton` components and some unit tests
https://github.com/user-attachments/assets/08add1b6-9888-48be-bc81-cdc21df3743c
https://github.com/user-attachments/assets/b0ed0007-9d9c-451d-a2af-eb86dbfc7d0a
https://github.com/user-attachments/assets/d3f2687f-14af-4700-8a6a-8205c083bda1
https://github.com/user-attachments/assets/bc0cfc3e-2dab-479f-815a-cb63cb3f411a
DISP-309
=> feat: Experimental buttons improvements

src/components/experimental/Table/Table.tsx
​To better indicate that the row is interactive
=> feat(table): add pointer as a cursor for interactive rows

src/components/experimental/index.ts
Forgot to export the new `Tooltip` component.
​
​
=> chore: exporting tooltip 😅

src/components/experimental/Tooltip/Tooltip.tsx
In this PR, we are changing the box shadow for the tooltip
​
​Better alignment with the specs from figma
=> fix: adding a box shadow for the tooltip

src/components/experimental/ComboBox/ComboBox.tsx, src/components/experimental/DateField/DateField.tsx, src/components/experimental/DatePicker/DatePicker.tsx, src/components/experimental/Field/FakeInput.ts, src/components/experimental/Field/Field.ts, src/components/experimental/Field/InnerWrapper.ts, src/components/experimental/Field/Label.ts, src/components/experimental/Field/Props.ts, src/components/experimental/Field/Wrapper.ts, src/components/experimental/NumberField/NumberField.tsx, src/components/experimental/NumberField/docs/NumberField.stories.tsx, src/components/experimental/RadioButton/RadioButton.tsx, src/components/experimental/Select/Select.tsx, src/components/experimental/TextField/TextField.tsx, src/components/experimental/TimeField/TimeField.tsx, src/components/experimental/TimeField/docs/TimeField.stories.tsx, src/components/experimental/index.ts, src/essentials/experimental/globalStyles.ts
1. Adds NumberField component
2. Makes label optional for some of the fields
​
https://github.com/user-attachments/assets/6b0b083d-d5e6-4c07-85a1-0a557810bc30
​
=> feat: add NumberField component

src/components/experimental/Field/FakeInput.ts, src/components/experimental/Field/Wrapper.ts
Fixes disabled state for a Select
​
​
=> fix(field): fix disabled state

src/components/experimental/Field/Label.ts, src/components/experimental/Select/Select.tsx, src/components/experimental/Select/docs/Select.stories.tsx
Add the `hideLabel` property to the experimental `Select` component
https://github.com/user-attachments/assets/8b4d32cf-ccbe-4277-aeb4-64051761ba95
​
Requirement for the `Frequency` select field in the recurrent trips form
=> feat: add hideLabel property on experimental Select
